permalink: /:month/:day/:year/:title

baseurl: /en

# Theme settings
theme:

  # Site name
  site_name: Yanping's English Homework

  # Google analytics UID
  google_analytics_uid: UA-27377274-3
  
  # Disqus shortname, for comments
  disqus_shortname: ypchenen

  # Number of featured posts on homepage
  homepage_featured: 1

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 3

  # Number of words to display in post summaries
  featured_wordcount: 20